export {default as dirt } from "./dirt.jpg"
export {default as gravel } from "./gravel.jpg"
export {default as log } from "./log.jpg"
export {default as magma } from "./magma.jpg"
export {default as rawWood } from "./raw-wood.jpg"
export {default as wood } from "./wood.png"
export {default as leocraft} from "./leocraft.jpg"
export {default as grass} from "./grass.jpg"